.TH "ARNO_FWFILTER" "1" "September 2005" "Michael Hanke" ""
.SH "NAME"
arno\-fwfilter \- a filter script to make iptables firewall logs more readable for humans
.SH "SYNOPSIS"
\fBarno\-fwfilter\fR [\fIOPTIONS\fR] 
.SH "DESCRIPTION"
\fBarno\-fwfilter\fR is a pipe filter script to make the firewall\-log better readable. Some usage examples are:
.TP
Static firewall log filtering:
arno-fwfilter < logfile
.TP
Realtime firewall logging on tty10:
tail \-\-follow <logfile> | arno-fwfilter >/dev/tty10 &
.SH "OPTIONS"
.TP
\fB\-\-help\fR, \fB\-h\fR
Print the available options.
.TP
\fB\-\-html\-output\fR, \fB\-o\fR
Use basic HTML to format the output
.TP
\fB\-\-no\-locations\fR, \fB\-l\fR
Disable to (try to) obtain the IP's geographical location. By default, 
http://www.hostip.info/ is visited to get this information.
.TP
\fB\-\-no\-colors\fR, \fB\-c\fR
Disable the use of colors in the output.
.TP
\fB\-\-single\-line\fR, \fB\-s\fR
Put all information about an event in a single line
.SH "SEE ALSO"
.BR iptables "(8)",
.BR arno\-iptables\-firewall "(8)"
.PP 
The
.I http://rocky.eld.leidenuniv.nl/
web site.
.SH "AUTHOR"
\fBarno\-fwfilter\fR was written by Arno van Amersfoort <arnova@rocky.eld.leidenuniv.nl>.
.PP 
This manual page was written by Michael Hanke <michael.hanke@gmail.com>,
for the Debian project (but may be used by others).
